compilers:
- compiler:
    spec: gcc@9.4.0
    paths:
      cc: /opt/ohpc/pub/compiler/gcc/9.4.0/bin/gcc
      cxx: /opt/ohpc/pub/compiler/gcc/9.4.0/bin/g++
      f77: /opt/ohpc/pub/compiler/gcc/9.4.0/bin/gfortran
      fc: /opt/ohpc/pub/compiler/gcc/9.4.0/bin/gfortran
    operating_system: rhel8
    target: x86_64
    modules:
      - gnu9/9.4.0
    environment:
      prepend_path:
        PATH: /opt/ohpc/pub/compiler/gcc/9.4.0/bin
        MANPATH: /opt/ohpc/pub/compiler/gcc/9.4.0/share/man
        INCLUDE: /opt/ohpc/pub/compiler/gcc/9.4.0/include
        LD_LIBRARY_PATH: /opt/ohpc/pub/compiler/gcc/9.4.0/lib64
    flags: {}
    extra_rpaths: []
