packages:
  all:
    'compiler:':
    - gcc@9.4.0
    providers:
      'mpi:':
      - openmpi@4.1.1
    target:
    - core2
  autoconf:
    externals:
    - modules:
      - autoconf-2.69-gcc-9.4.0-ijgeghe
      prefix: /home/public/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/autoconf-2.69-ijgegheosdo5iqelkhhqy3v3mvrvvydh
      spec: autoconf@2.69%gcc@9.4.0
  automake:
    externals:
    - modules:
      - automake-1.16.5-gcc-9.4.0-raergs3
      prefix: /home/public/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/automake-1.16.5-raergs3uxwrrvemyriwaqkkapyjj3sj4
      spec: automake@1.16.5%gcc@9.4.0
  binutils:
    externals:
    - modules:
      - binutils-2.37-gcc-9.4.0-44se45o
      prefix: /home/public/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/binutils-2.37-44se45ocvpio22yagfdbnzt6uyjp7ggy
      spec: binutils@2.37%gcc@9.4.0
  curl:
    externals:
    - modules:
      - curl-7.85.0-gcc-9.4.0-qbney7y
      prefix: /home/public/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/curl-7.85.0-qbney7yudyfu2upzsjetbhteq3cy3ego
      spec: curl@7.85.0%gcc@9.4.0
  diffutils:
    externals:
    - modules:
      - diffutils-3.8-gcc-9.4.0-uvi2god
      prefix: /home/public/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/diffutils-3.8-uvi2god6p2utgfx3rw3haxly6a37v4tj
      spec: diffutils@3.8%gcc@9.4.0
  findutils:
    externals:
    - modules:
      - findutils-4.9.0-gcc-11.2.0-wrg5qsj
      prefix: /opt/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/findutils-4.9.0-fkc3udaec67g75xligh23s3ockmw5lmo
      spec: findutils@4.9.0%gcc@9.4.0
  gmake:
    externals:
    - modules:
      - gmake-4.3-gcc-11.2.0-oefby2a
      prefix: /opt/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/gmake-4.3-vhikrkueco7tjdc2h3iw2w6bfwben3ea
      spec: gmake@4.3%gcc@9.4.0
  krb5:
    externals:
    - modules:
      - krb5-1.19.3-gcc-9.4.0-vtl5siq
      prefix: /home/public/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/krb5-1.19.3-vtl5siqtxaulz7dq63hfhfxjvnlolml5
      spec: krb5@1.19.3%gcc@9.4.0
  m4:
    externals:
    - modules:
      - m4-1.4.19-gcc-9.4.0-mi3u6ba
      prefix: /home/public/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/m4-1.4.19-mi3u6bahlct7zg4dxqmpetsjurrcihc3
      spec: m4@1.4.19%gcc@9.4.0
  mpi:
    buildable: false
  openmpi:
    externals:
    - modules:
      - gnu9/9.4.0
      - hwloc/2.5.0
      - ucx/1.11.2
      - libfabric/1.13.0
      - openmpi4/4.1.1
      spec: openmpi@4.1.1
  openssl:
    externals:
    - modules:
      - openssl-1.1.1q-gcc-9.4.0-6zaz2vm
      prefix: /home/public/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/openssl-1.1.1q-6zaz2vmcy666hqsqrrvxru4damhk7soo
      spec: openssl@1.1.1q%gcc@9.4.0
  pkgconf:
    externals:
    - modules:
      - pkgconf-1.8.0-gcc-9.4.0-mnuz4ik
      prefix: /home/public/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/pkgconf-1.8.0-mnuz4ikmrmk224kmljhb6xg2iocp4vn2
      spec: pkgconf@1.8.0%gcc@9.4.0
  tar:
    externals:
    - modules:
      - tar-1.34-gcc-9.4.0-jnb6yno
      prefix: /home/public/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/tar-1.34-jnb6ynovyvuknwpdhyuyn72wcjgx24ba
      spec: tar@1.34%gcc@9.4.0
  texinfo:
    externals:
    - modules:
      - texinfo-6.5-gcc-11.2.0-pdwv2ml
      prefix: /opt/spack/opt/spack/linux-rhel8-zen2/gcc-9.4.0/texinfo-6.5-kxilaplzlw72pbtkvqsrp5capwfjt3uj
      spec: texinfo@6.5%gcc@9.4.0
